### ISSUE TITLE
Add `minVersion` to Requirement class

### ISSUE THREAD

**Issue by onigoetz** [erksch/semver4k#1]
Hi,

Thanks for this library, I am currently in the process of migrating a JavaScript application to Java and this saves me quite some time.

I'm currently using this NPM package for semver ( https://www.npmjs.com/package/semver ) and one of the methods I use is `minVersion` which for a range / requirement gives me the minimum version that matches that requirement.

the feature works by analyzing the comparators of the range / requirements : https://github.com/npm/node-semver/blob/master/ranges/min-version.js in semver4k this field is private and I can't implement this feature on my side.

Is it possible to implement this feature in the library ?

I can try to implement this and make a pull-request if that's something you'd be interested in although I'm not fluent in Kotlin and it wouldn't be as clean and idiomatic as what you would do.

**Comment by Legion2** [comment]
Released in 4.1.0
